package com.chucknorris;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.hamcrest.CoreMatchers.containsString;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThat;

public class ChuckNorrisTest {
	@Test public void testGetFact() {
		ChuckNorris ck = new ChuckNorris();
		String fact = ck.getFact();
		assertThat(fact, containsString("Chuck Norris"));
	}
}
